### ISSUE TITLE
Public Pub fails

### ISSUE THREAD

**Issue by No9** [ssbc/phoenix#300]
After publishing an image the following errors occurred:

```
/opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:227
        remotes[id].blobs.get(f.id),
                   ^
TypeError: Cannot read property 'blobs' of undefined
    at /opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:227:20
    at job (/opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:58:5)
    at next (/opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:205:19)
    at /opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:185:34
    at each (/opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:22:5)
    at /opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:176:7
    at job (/opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:58:5)
    at EventEmitter.<anonymous> (/opt/local/lib/node_modules/scuttlebot/plugins/blobs.js:139:7)
    at EventEmitter.emit (events.js:117:20)
    at /opt/local/lib/node_modules/scuttlebot/index.js:118:16
[root@a5e56387-8f37-42a3-94de-0ff2ceee29af /root/services/phoenix]#  remotes[id].blobs.get(f.id),
bash: syntax error near unexpected token f.id'
```

**Comment by pfraze** [comment]
you happen to catch what version of sbot you were running?

**Comment by No9** [comment]
Yeah so this was on scuttlebot@2.1.9 
Upgraded as per IRC dicussion. Will let you know if I see it again.

**Comment by pfraze** [comment]
@No9 have you experienced this again?

**Comment by No9** [comment]
Nope closing

**Comment by pfraze** [comment]
thanks!
